---
language: python
services: docker

# Spin off separate builds for each of the following versions of Ansible
env:
  matrix:
    # Minumum required Ansible version for Molecule
    - ANSIBLE_PACKAGE='ansible==2.5.0'
    # Latest ansible
    - ANSIBLE_PACKAGE='ansible'

# Cache Ansible and Molecule to speed things up
cache:
  - pip

install:
  # Install Ansible, Molecule and docker-py
  - pip install "$ANSIBLE_PACKAGE" molecule docker

  # Log Docker, Ansible and Molecule version
  - docker --version
  - ansible --version
  - molecule --version

before_script:
  - cd .. && mv ansible-role-maxmind-geoip jgeusebroek.maxmind-geoip && cd jgeusebroek.maxmind-geoip

script:
  # Start test
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/